# Generated by Django 4.2.5 on 2023-09-12 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_members_joined_data_members_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='joined_data',
            new_name='joined_date',
        ),
    ]
